
package com.soacookbook.ns.credit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditAuthorizer", targetNamespace = "http://ns.soacookbook.com/credit")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditAuthorizer {


    /**
     * 
     * @param creditCard
     * @return
     *     returns com.soacookbook.ns.credit.Authorization
     */
    @WebMethod
    @WebResult(name = "authorization", targetNamespace = "http://ns.soacookbook.com/credit", partName = "authorization")
    public Authorization authorize(
        @WebParam(name = "creditCard", targetNamespace = "http://ns.soacookbook.com/credit", partName = "creditCard")
        CreditCard creditCard);

}
