
package com.soacookbook.ns.credit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CreditService", targetNamespace = "http://ns.soacookbook.com/credit", wsdlLocation = "http://localhost:8080/WebServiceComplexSchema/wsdl/ch03/Credit.wsdl")
public class CreditService
    extends Service
{

    private final static URL CREDITSERVICE_WSDL_LOCATION;
    private final static WebServiceException CREDITSERVICE_EXCEPTION;
    private final static QName CREDITSERVICE_QNAME = new QName("http://ns.soacookbook.com/credit", "CreditService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebServiceComplexSchema/wsdl/ch03/Credit.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREDITSERVICE_WSDL_LOCATION = url;
        CREDITSERVICE_EXCEPTION = e;
    }

    public CreditService() {
        super(__getWsdlLocation(), CREDITSERVICE_QNAME);
    }

    public CreditService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREDITSERVICE_QNAME, features);
    }

    public CreditService(URL wsdlLocation) {
        super(wsdlLocation, CREDITSERVICE_QNAME);
    }

    public CreditService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREDITSERVICE_QNAME, features);
    }

    public CreditService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreditAuthorizer
     */
    @WebEndpoint(name = "CreditAuthorizerPort")
    public CreditAuthorizer getCreditAuthorizerPort() {
        return super.getPort(new QName("http://ns.soacookbook.com/credit", "CreditAuthorizerPort"), CreditAuthorizer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditAuthorizer
     */
    @WebEndpoint(name = "CreditAuthorizerPort")
    public CreditAuthorizer getCreditAuthorizerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ns.soacookbook.com/credit", "CreditAuthorizerPort"), CreditAuthorizer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREDITSERVICE_EXCEPTION!= null) {
            throw CREDITSERVICE_EXCEPTION;
        }
        return CREDITSERVICE_WSDL_LOCATION;
    }

}
